=== AOSC-Tracking/gegl/opgen/geglopgen.dtd
<!-- DTD for gegl opgen -->

<!ELEMENT PointOp (description?,
                   author,
                   copyright,
                   license+,
                   libraries?,
                   includes?,
                   variables?,
                   constructor?,
                   destructor?,
                   prepare?,
                   PointProcessor+)
>

<!ATTLIST PointOp    name        ID     #REQUIRED>
<!ATTLIST PointOp    arguments   CDATA  #REQUIRED>
<!ATTLIST PointOp    language    (c|cpp|perl|python|lisp) "c">

<!ELEMENT PointProcessor (variables?,
                          setup?,
                          per_pixel?,
                          per_color?,
                          per_alpha?,
                          cleanup?)
>

<!ATTLIST PointProcessor    precision   (U8|U16|FLOAT|all) 'all'>
<!ATTLIST PointProcessor    colormodel
         (BW|RGB|XYZ|CMYK|INDEXED|additive|subtractive|intensity|all)  'all'>


<!ELEMENT description    (#PCDATA)*>
<!ELEMENT author         (#PCDATA)*>
<!ELEMENT copyright      (#PCDATA)*>
<!ELEMENT variables      (#PCDATA)*>
<!ELEMENT license        (#PCDATA)*>
<!ELEMENT constructor    (#PCDATA)*>
<!ELEMENT destructor     (#PCDATA)*>
<!ELEMENT prepare        (#PCDATA)*>
<!ELEMENT setup          (#PCDATA)*>
<!ELEMENT per_pixel      (#PCDATA)*>
<!ELEMENT per_color      (#PCDATA)*>
<!ELEMENT per_alpha      (#PCDATA)*>
<!ELEMENT cleanup        (#PCDATA)*>

=== AOSC-Tracking/gegl/opgen/blend.xml
<?xml version="1.0"?>

<!DOCTYPE PointOp SYSTEM "geglopgen.dtd">


<PointOp name="blend"  arguments="const Buffer src1, const Buffer src2">
  <description>
The blend operator blends two pixel sources together based on their alpha channels. src1 over src2.
  </description>
  <author>Jay Cox</author>
  <copyright>2001, Jay Cox</copyright>
  <license>GPL</license>

  <variables>
    /* This function don't need no variables */
  </variables>
  <constructor>
  </constructor>
  <destructor>
  </destructor>
  <PointProcessor precision="all" colormodel="all">
    <variables>
    /* This function don't need no variables */
    </variables>
    <per_pixel>     
    /* This function don't need no per pixel */
    </per_pixel>
    <per_color>
<![CDATA[
    dest = (src1 * src1_alpha + 
            src2 * ((CHANNEL_MAX - src1_alpha) * src2_alpha)) /
          (CHANNEL_MAX - (CHANNEL_MAX - src1_alpha)*(CHANNEL_MAX - src2_alpha))
]]>
    </per_color>
    <per_alpha>
<![CDATA[
      dest = src1 + (CHANNEL_MAX - src1) * src2;
]]>
    </per_alpha>
    <cleanup>
    /* no cleanup needed for this function */
    </cleanup>
  </PointProcessor>
</PointOp>

=== AOSC-Tracking/gegl/opgen/test-op.xml
<?xml version="1.0"?>

<!DOCTYPE PointOp SYSTEM "geglopgen.dtd">


<PointOp name="testopgen"  arguments="const IMAGE src1, const IMAGE src2">
  <description>
The subtract function subtracts the values of each pixel in the second image
buffer from the corosponding pixel value in the first image buffer placing
the results in the dest image buffer.
  </description>
  <author>Jay Cox</author>
  <copyright>2000, Jay Cox</copyright>
  <license>GPL</license>

  <variables>
    /* This function don't need no variables */
  </variables>
  <constructor>
  </constructor>
  <destructor>
  </destructor>
  <PointProcessor precision="FLOAT" colormodel="RGB">
    <variables>
    /* This function don't need no variables */
    </variables>
    <per_pixel>     
    /* This function don't need no per pixel */
    </per_pixel>
    <per_color>
<![CDATA[
       dest = CHANNEL_CLAMP((SignedPromote)src1 - src2);
]]>
    </per_color>
    <per_alpha>
<![CDATA[
      dest = MIN(src1, src2);
]]>
    </per_alpha>
    <cleanup>
    /* no cleanup needed for this function */
    </cleanup>
  </PointProcessor>
</PointOp>
